version: "2"

plugins:
  codenarc:
    enabled: true
  editorconfig:
    enabled: true
    config:
      editorconfig: .editorconfig
    exclude_patterns:
    - "doc/**/images/"
  fixme:
    enabled: true
    config:
      strings:
      - TODO
      - FIXME
  markdownlint:
    enabled: true
    checks:
      MD013:
        enabled: false
  shellcheck:
    enabled: true
