

language: groovy

matrix:
  include:
    - jdk: openjdk11
    - jdk: openjdk10

install: make code.build

before_script: make code.lint

script: make test.unit

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
