

language: groovy

env:
  - CI=true

install: make deps.install

before_script: make static.lint

script: make test.unit

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
